[2025-10-02T13:06:39.430+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-02T13:06:39.445+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main.run_write_postgres manual__2025-10-02T13:06:30.896970+00:00 [queued]>
[2025-10-02T13:06:39.451+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main.run_write_postgres manual__2025-10-02T13:06:30.896970+00:00 [queued]>
[2025-10-02T13:06:39.451+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-10-02T13:06:39.463+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_write_postgres> on 2025-10-02 13:06:30.896970+00:00
[2025-10-02T13:06:39.470+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=7532) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-02T13:06:39.471+0000] {standard_task_runner.py:63} INFO - Started process 7534 to run task
[2025-10-02T13:06:39.472+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'main', 'run_write_postgres', 'manual__2025-10-02T13:06:30.896970+00:00', '--job-id', '94', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpmb9_56oi']
[2025-10-02T13:06:39.473+0000] {standard_task_runner.py:91} INFO - Job 94: Subtask run_write_postgres
[2025-10-02T13:06:39.509+0000] {task_command.py:426} INFO - Running <TaskInstance: main.run_write_postgres manual__2025-10-02T13:06:30.896970+00:00 [running]> on host 5adecdfd8c83
[2025-10-02T13:06:39.571+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='main' AIRFLOW_CTX_TASK_ID='run_write_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-10-02T13:06:30.896970+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-02T13:06:30.896970+00:00'
[2025-10-02T13:06:39.573+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-02T13:06:43.571+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-02T13:06:43.572+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/main.py", line 125, in write_postgres
    df3.write \
    ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 6204, in __getattr__
    return object.__getattribute__(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataFrame' object has no attribute 'write'
[2025-10-02T13:06:43.589+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=main, task_id=run_write_postgres, run_id=manual__2025-10-02T13:06:30.896970+00:00, execution_date=20251002T130630, start_date=20251002T130639, end_date=20251002T130643
[2025-10-02T13:06:43.602+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 94 for task run_write_postgres ('DataFrame' object has no attribute 'write'; 7534)
[2025-10-02T13:06:43.621+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-02T13:06:43.636+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-02T13:06:43.639+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
